# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-22 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('tasks', '0003_auto_20171022_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='groups',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
    ]
