# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20171024_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Done')], max_length=1),
        ),
    ]
